//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class STOCKTBL
    {
        public string DEALID { get; set; }
        public string GOODSID { get; set; }
        public string GOODSNM { get; set; }
        public int PRICE { get; set; }

        [Required(ErrorMessage = "在庫数を入力してください")]
        [Range(0, 2147483647, ErrorMessage = "適切な数量を入力してください")]
        public int STOCK { get; set; }
        public int TPRICE { get; set; }
        public System.DateTime LASTUDT { get; set; }
    }
}
