//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STOCKTBL
    {
        public string DEALID { get; set; }
        public string GOODSID { get; set; }
        public string GOODSNM { get; set; }
        public string PRICE { get; set; }
        public string STOCK { get; set; }
        public string TPRICE { get; set; }
        public System.DateTimeOffset LASTUDT { get; set; }
    }
}
